version: "3"
services:
  db:
    image: "bitnami/mongodb:latest"
    ports:
      - '27017:27017'
    networks:
      - net
    environment:
      MONGODB_USERNAME: renatasette
      MONGODB_PASSWORD: renata7
      MONGODB_DATABASE: renatasette_db
    volumes:
      - './containers/mongo:/data/db'
networks:
  net: